export const STRINGS = {
  upload: {
    title: "Document Intelligence Upload",
    dragDrop: "Drag and drop your document here, or click to browse",
    supportText: "Supports PDF, DOCX, TXT, and Images",
    started: "Upload Started",
    startedMsg: "File uploaded successfully. Processing started.",
    failed: "Upload Failed",
    failedMsg: "Failed to upload the file.",
    success: "Processing Successful",
    successMsg: "Document has been processed successfully.",
    procFailed: "Processing Failed",
    procFailedMsg: "Failed to process the document.",
    trackerTitle: "Live Pipeline Tracker",
    steps: {
      PENDING: "Verified & queued",
      EXTRACTING: "Content parsing",
      ANALYZING: "Neural mapping",
      PERSISTING: "Saving to DB",
      COMPLETED: "Intelligence ready",
    },
  },
  sidebar: {
    dashboard: "Dashboard",
    documents: "Documents",
    analytics: "Analytics",
    settings: "Settings",
    brand: "AIPCPP",
    brandSub: "Neural Core",
    mode: "Onboarding Mode",
  },
  details: {
    title: "Document Details",
    deleteConfirm: "Are you sure you want to delete this document?",
    deleted: "Deleted",
    deletedMsg: "Document deleted successfully.",
    error: "Error",
    errorMsg: "Failed to delete document.",
    back: "Back to Dashboard",
    timeline: "Timeline (History)",
    noData: "No data available for the latest version.",
    noTimeline: "No timeline items found.",
  },
};
