export const STRINGS = {
  upload: {
    title: "Document Intelligence Upload",
    dragDrop: "Drag and drop your document here, or click to browse",
    supportText: "Supports PDF, DOCX, TXT, and Images",
    started: "Upload Started",
    startedMsg: "File uploaded successfully. Processing started.",
    fileTooLarge: "File Too Large",
    fileTooLargeMsg: "File size exceeds the 50MB limit. Please upload a smaller file.",
    failed: "Upload Failed",
    failedMsg: "Failed to upload the file.",
    success: "Processing Successful",
    successMsg: "Document has been processed successfully.",
    procFailed: "Processing Failed",
    procFailedMsg: "Failed to process the document.",
    trackerTitle: "Live Pipeline Tracker",
    steps: {
      UPLOADING: "Uploading file",
      PENDING: "Verified & queued",
      PROCESSING: "AI analysis",
      COMPLETED: "Summary generation completed",
    },
    completeTitle: "Upload Complete!",
    uploadAnother: "Upload another",
    readyMessage:
      "Your document is ready. Click below to view the AI-generated summary and details.",
    viewDocument: "View Document",
    failedRetry: "Upload failed. Please try again.",
  },
  search: {
    semanticPlaceholder: "Ask a question about your documents...",
    defaultPlaceholder: "Search files by name, type, or tag...",
    semantic: "Semantic",
    filter: "Filter",
    all: "All",
    newest: "Newest",
    oldest: "Oldest",
    filterTypeLabel: "Type:",
    searchAria: "Search documents",
    filterAria: "Filter documents",
    sortAria: "Sort documents",
    toggleSemanticAria: "Toggle semantic search",
  },
  sidebar: {
    dashboard: "Dashboard",
    documents: "Documents",
    analytics: "Analytics",
    settings: "Settings",
    brand: "AIPCPP",
    brandSub: "Neural Core",
    mode: "Onboarding Mode",
    expandSidebar: "Expand sidebar",
    collapseSidebar: "Collapse sidebar",
    brandInitial: "A",
    uploadDocument: "Upload Document",
    userName: "Farhan Mahi",
    userInitials: "FM",
  },
  details: {
    title: "Document Details",
    deleteConfirm: "Are you sure you want to delete this document?",
    deleted: "Deleted",
    deletedMsg: "Document deleted successfully.",
    error: "Error",
    errorMsg: "Failed to delete document.",
    back: "Back to Dashboard",
    timeline: "Timeline (History)",
    noData: "No data available for the latest version.",
    noTimeline: "No timeline items found.",
    errorTitle: "Error Loading Document",
    errorBody: "We couldn't retrieve the details for this document. It may have been deleted.",
    goBack: "Go Back",
    headerIdPrefix: "ID:",
    createOverride: "Create Override",
    editDetails: "Edit Details",
    deleting: "Deleting",
    delete: "Delete",
    form: {
      titleLabel: "Document Title",
      titlePlaceholder: "e.g., Annual Financial Report 2024",
      categoryLabel: "Category",
      categoryPlaceholder: "e.g., Finance, Legal, HR",
      summaryLabel: "Summary",
      summaryPlaceholder: "Provide a comprehensive summary...",
      tagsLabel: "Tags (comma-separated)",
      tagsPlaceholder: "e.g., revenue, growth, forecast",
      tagsDescription: "Separate tags with commas",
      saveAsNewVersion: "Save as new version (retains historical version)",
      cancel: "Cancel",
      saveChanges: "Save Changes",
    },
    info: {
      title: "Title",
      category: "Category",
      summary: "Summary",
      tags: "Tags",
      notAvailable: "N/A",
    },
    timelineVersion: "Version",
    timelineDeleteTitle: "Delete version override",
    timelineNoSummary: "No summary text.",
    errorBoundaryMessage: "An unexpected error occurred in this module.",
    errorBoundaryRetry: "Retry",
  },
  footer: {
    version: "AIPCPP Neural Core v1.0.0",
    systemHealth: "System Health",
    compliance: "Compliance",
    docs: "Docs",
  },
  nav: {
    properties: "Properties",
    applications: "Applications",
    people: "People",
    leases: "Leases",
    payments: "Payments",
    tasks: "Tasks",
    rentReceipts: "Rent Receipts",
  },
  dashboard: {
    loading: "Loading documents...",
    loadError: "Failed to load documents.",
    empty: "No documents found.",
    uploadAria: "Upload new document",
    uploadTitle: "Process new document",
    uploadSubtitle: "Neural Hub Active",
    synthesis: "Synthesis",
    matches: "Matches",
    score: "Score",
    viewDetails: "View Details",
    delete: "Delete",
    documentOptions: "Document options",
  },
};
